language: go
go_import_path: arp242.net/goimport
go:
  - 1.8.x
  - 1.9.x
cache:
  directories:
    - $HOME/gopath/pkg
install:
  - dep ensure
script:
  - cd $HOME/gopath/src/arp242.net/goimport
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
