language: go
go_import_path: arp242.net/goimport
go:
  - 1.9.x
  - latest
notifications:
  email: false
cache:
  directories:
    - $HOME/gopath/pkg
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - cd $HOME/gopath/src/arp242.net/goimport
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
